// This file is automatically generated. Do not edit it directly.
<<<<<<< HEAD
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xezltbklfasklpksimlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhlemx0YmtsZmFza2xwa3NpbWxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0OTE5NzcsImV4cCI6MjA2MTA2Nzk3N30._JIxxj2hxtuEqCzdK7mkX2oRX2kJ7WQmQ3UA-jToO54";
=======
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://xezltbklfasklpksimlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhlemx0YmtsZmFza2xwa3NpbWxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0OTE5NzcsImV4cCI6MjA2MTA2Nzk3N30._JIxxj2hxtuEqCzdK7mkX2oRX2kJ7WQmQ3UA-jToO54";
>>>>>>> tempRepo/main

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

<<<<<<< HEAD
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
=======
export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
);
>>>>>>> tempRepo/main
